### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by yohanboniface** [Legilibre/Archeo-Lex#43]
Lancé sur un scaleway tout neuf les commandes indiquées dans le README:

```
python -m legi.download ./tarballs
python -m legi.tar2sqlite legi.sqlite ./tarballs
```

Et ça plante (au bout d'une petite heure à la louche) pendant le tar2sqlite:

```
deleted 381 rows based on liste_suppression_legi.dat: {"articles": 85, "liens": 137, "sections": 7, "sommaires": 128, "textes_structs": 12, "textes_versions": 12}
last_update is now set to 20170629-205629
> Processing legi_20170630-204118.tar.gz...
duplicate_files
    (u'other_cid', u'JORFTEXT000033578386')
    (u'sous_dossier', u'texte/struct')
    (u'other_dossier', u'TNC_non_vigueur')
    (u'other_mtime', 1498848089)
    (u'cid', u'JORFTEXT000033578386')
    (u'dossier', u'TNC_en_vigueur')
    (u'mtime', 1498762615)
    (u'id', u'LEGITEXT000033583880')
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/venv/lib/python2.7/site-packages/legi/tar2sqlite.py", line 429, in <module>
    main()
  File "/root/venv/lib/python2.7/site-packages/legi/tar2sqlite.py", line 405, in main
    process_archive(db, args.directory + '/' + archive_name)
  File "/root/venv/lib/python2.7/site-packages/legi/tar2sqlite.py", line 206, in process_archive
    'other_mtime': mtime,
  File "/root/venv/local/lib/python2.7/site-packages/legi/utils.py", line 107, in insert
    """.format(or_clause, table, keys, placeholders), values)
sqlite3.IntegrityError: UNIQUE constraint failed: duplicate_files.id, duplicate_files.sous_dossier, duplicate_files.cid, duplicate_files.dossier
```

Une idée ou je creuse? :)

**Comment by Changaco** [comment]
https://github.com/Legilibre/legi.py/issues/17

**Comment by yohanboniface** [comment]
Merci, je vais suivre là-bas.
