### ISSUE TITLE
Pas de texte avec cet ID ou CID

### ISSUE THREAD

**Issue by revolunet** [Legilibre/Archeo-Lex#49]
Bonjour,

petit souci  ce matin :)

```python
Dernière mise à jour de la base LEGI : 2018-02-01T19:55:53+01:00
Traceback (most recent call last):
  File "./archeo-lex", line 148, in <module>
    principal(docopt(aide, help=False))
  File "./archeo-lex", line 145, in principal
    creer_historique_legi(data['textes'], data['format'], data['dossier'], data['cache'], data['bddlegi'])
  File "/code/marcheolex/exporterlegi.py", line 89, in creer_historique_legi
    creer_historique_texte(texte, format, dossier, cache, bdd)
  File "/code/marcheolex/exporterlegi.py", line 135, in creer_historique_texte
    raise Exception('Pas de texte avec cet ID ou CID')
Exception: Pas de texte avec cet ID ou CID
```

**Comment by revolunet** [comment]
erreur désolé

**Comment by revolunet** [comment]
en fait j'ai cette erreur en spécifiant `--textes=code-du-travail` ex : 

`./archeo-lex --bddlegi=/tarballs/legilibre.sqlite --historique=git --textes=code-travail`
